title: "Sujeet's Java Blog"
description: "Java, Spring Boot, Microservices, and Backend Best Practices"
author: "Sujeet Prajapati"
theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title
