title: "Sujeet Prajapati — Java Developer"
description: "Senior Java developer portfolio: Spring Boot, Microservices, AWS, PostgreSQL, Kafka. Blog + Projects + Resume."
author: "Sujeet Prajapati"
url: "" # set to https://<your-username>.github.io later
baseurl: "" # leave empty for user.github.io root
theme: null
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
collections:
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-sitemap
